function stats = CalcStats(restore)
error_list = [];
ok_list = [];
for i = 1:length(restore)
    if strcmp(restore(i).Flag, 'OK!')
        ok_list(end + 1) = i;
    else
        error_list(end + 1) = i;
    end
dMSE = ([restore(:).AccSat] - [restore(:).AccRest])./ [restore(:).AccSat];
[min_val, min_id] =  min(dMSE(ok_list));
[max_val, max_id] =  max(dMSE(ok_list));
[val, idx] = sort(dMSE(ok_list));
srt = ok_list(idx);

stats = struct('Error', error_list, ...
    'OK', ok_list, ...
    'Mean', mean(dMSE(ok_list)), ...
    'Median', median(dMSE(ok_list)), ...
    'Min', min_val, ...
    'Max', max_val, ...
    'argMin', ok_list(min_id), ...
    'argMax', ok_list(max_id), ...
    'srt', srt, ...
    'dMSE', dMSE);
end